config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "js", to: "home#js"
  get "js2", to: "home#js2"
  get "/member/:id", to: "member#show", as: 'member_show'
  get "/edit_description/:id", to: "member#edit_description", as: 'edit_descriptions'
  patch "/update_description/:id", to: "member#update_description", as: "update_description"
  resources :work_expriences
  resources :connections

end

app/views/shared/_footer.html.erb
<div class="row border-top mt-4"> 
 <div class="col-4 text-muted"> Company@ 24-25</div>
 <div class="col-4 "> 
  <div class="h5"> Featurs </div>
  <div class="row text-muted ms-1">About us </div>
  <div class="row text-muted ms-1">Cantect us </div>
  <div class="row text-muted ms-1">Our Misstion </div>
 </div>
  <div class="col-4 "> 
  <div class="h5"> Resources </div>
  <div class="row text-muted ms-1">About us </div>
  <div class="row text-muted ms-1">Cantect us </div>
  <div class="row text-muted ms-1">Our Misstion </div>
 </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary color-white">
  <div class="container-fluid">
    <a class="navbar-brand  text-white" href="<%= root_path %>">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="<%= member_show_path(current_user) %>">Perfile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="<%= connections_path %>">Networks </a>
        </li>
        <li class="nav-item">
           <a class="nav-link active text-white" aria-current="page" href="<%= destroy_user_session_path %>">sign out</a>
          <% else %>
           <a class="nav-link active text-white" aria-current="page" href="<%= new_user_registration_path %>">sign in</a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>