config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "js", to: "home#js"
  get "js2", to: "home#js2"
  get "/member/:id", to: "member#show", as: 'member_show'
  get "/edit_description/:id", to: "member#edit_description", as: 'edit_descriptions'
  patch "/update_description/:id", to: "member#update_description", as: "update_description"
  resources :work_expriences
  resources :connections

end

app/controllers/member_controller.rb
class MemberController < ApplicationController
	def show
		@member = User.find(params[:id])
    @connection = Connection.find_by(connected_user_id: @member .id)
    @connections_count = Connection.where(status: "accepted")
                               .where("user_id = ? OR connected_user_id = ?", @member.id, @member.id)
	end
	def edit_description
		@member = User.find(params[:id])
	end
def update_description
	byebug
  @member = User.find(params[:id])
  
  if @member.update(about: params[:user][:about])
    render turbo_stream: turbo_stream.replace(
      "member-description",
      partial: "member/member_description",
      locals: { user: @member }
    )
  else
    render turbo_stream: turbo_stream.replace(
      "member-description-form",
      partial: "member/edit_description_form",
      locals: { user: @member }
    )
  end
end


end

app/helpers/member_helper.rb
module MemberHelper
end

app/views/member/_description_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"  data-controller="bs-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="member-description-form">
        <%= form_with model: @member, url: update_description_path(@member), method: :patch, data: { turbo_stream: true } do |form| %>
        <%= form.label :about %>
        <%= form.text_area :about, value: @member.about, class:"w-100 min-vh-75",  style:"width: 100% !important; min-height: 50vh !important;" %>
      </div>
      <div class="modal-footer">
      	 <%= form.submit "save change", data: {action: 'click->bs-modal#submitEnd'}, class:"btn btn-primary"  %>
         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
         <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/member/_member_description.html.erb
<span id="member-description"><%= member.about %></span>

app/views/member/edit_description.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "description_modal", user: @member %>
<% end %>

app/views/member/edit_descriptions.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "description_modal", user: @member %>
<% end %>

app/views/member/show.html.erb
<div class="row border-top mt-2 m-5 shadow">
  <div class="col-3">
    <%= image_tag("user_img.jpeg", class: "mx-auto mt-3", style: "width: 150px;") %>
  </div>
  <div class="col-8 mt-4">
    <div class="row h4">
      <%= @member.user_name %>
    </div>
    <div class="row">
      <%= @member.perfile_title %>
    </div>
    <div id="user-connections-status">
      <% if user_signed_in? &&  @member !=current_user %>
        <% if current_user.check_if_already_connected?(current_user, @member) %>
          <%= button_to 'Connect', connections_path(connected_user_id: @member.id), method: :post, class: 'btn btn-primary' %>
        <% elsif @connection %>
          <% case @connection.status %>
            <% when "pending" %>
              <%= button_to 'Pending', connection_path(@member.id), method: :delete, class: 'btn btn-danger' %>
            <% when "accepted" %>
              <%= button_to 'Connected', connection_path(@member.id), method: :delete, class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="row text-primary">
      <%= @member.user_locations %>
    </div>
    <div class="row text-primary">
      Total count : 
      <%= @connections_count.count %>
    </div>
  </div>
  
  <div class="row mt-4 border-top m-1">
    <div class="row h3">
      About
    </div>
    <div class="row border-bottom">
      <%= render "member_description", member: @member %>

    </div>
  </div>
</div>

<div class="card mx-5">
  <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
      <div class="h4">Work Experiences</div>
      <div class="d-flex justify-content-center">
        <%= link_to new_work_exprience_path, data: { turbo_stream: false } do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
          </svg>
        <% end %>
        Add Work Experiences
      </div>
      <div>
        <%= link_to edit_work_exprience_path, data: { turbo_stream: false } do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
          </svg>
        <% end %>
        Edit Work Experiences
      </div>
    </div>
  </div>
<% if user_signed_in? && @member.work_expriences.present? %>
  <% @member.work_expriences.each do |work_exprience| %>
    <div class="card-body">
        <div class="row">
          <div class="col-10 h5">
            <%= work_exprience.job_title %>
          </div>
          <% if  @member ==current_user %>
          <div class="col-2 h5">
         <%= link_to edit_work_exprience_path(work_exprience), data: { turbo_stream: false } do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
          </svg>
        <% end %>
        <%= link_to work_exprience_path(work_exprience), data: { turbo_method: :delete, turbo_stream: false } do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-trash" viewBox="0 0 16 16">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
        </svg>
        <% end %>
          </div>
          <% end %>
          <div class="p"><%= work_exprience.company %> </div>
          <div class="p"><%= work_exprience.employment_type %> </div>
          <div class="p"><%= work_exprience.location %> </div> 
          <div class="p">
            <%= work_exprience.start_date.strftime("%d-%m-%Y") %> - 
            <%= work_exprience.end_date.present? ? work_exprience.end_date.strftime("%d-%m-%Y") : "present" %> 
            (<%= work_exprience.count_exprinces_date %>)
          </div>
        </div>
      </div>
  <% end %>
   <% end %>
</div>